gestionRapportVisites/src/Entity/Offrir.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
// use Symfony\Component\Serializer\Annotation\Groups;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Reference un medicament et sa quantite offerte a un praticien lors d'une visite
 * 
 * @ORM\Entity(repositoryClass="App\Repository\OffrirRepository")
 * @ORM\Table(uniqueConstraints={
 *       @ORM\UniqueConstraint(name="medicament_offert_unique", columns={"rapport_visite_id","medicament_id"})
 *       })
 */
class Offrir
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * 
     * @serializer\Groups({"medicament"})
     */
    private $id;

    /**
     * Quantite de medicament offert
     * 
     * @var int
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * 
     * @serializer\Groups({"medicament"})
     */
    private $off_qte;

    /**
     * Compte-rendu de la visite
     * 
     * @var rapportVisite
     * @ORM\ManyToOne(targetEntity="App\Entity\RapportVisite", inversedBy="offrirs")
     * @ORM\JoinColumn(nullable=false)
     * 
     * @serializer\Groups({"medicament"})
     */
    private $rapportVisite;

    /**
     * @var medicament
     * @ORM\ManyToOne(targetEntity="App\Entity\Medicament", inversedBy="offrirs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $medicament;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOffQte(): ?int
    {
        return $this->off_qte;
    }

    public function setOffQte(int $off_qte): self
    {
        $this->off_qte = $off_qte;

        return $this;
    }

    public function getRapportVisite(): ?RapportVisite
    {
        return $this->rapportVisite;
    }

    public function setRapportVisite(?RapportVisite $rapportVisite): self
    {
        $this->rapportVisite = $rapportVisite;

        return $this;
    }

    public function getMedicament(): ?Medicament
    {
        return $this->medicament;
    }

    public function setMedicament(?Medicament $medicament): self
    {
        $this->medicament = $medicament;

        return $this;
    }
}

gestionRapportVisites/src/Entity/Praticien.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PraticienRepository")
 */
class Praticien
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $pra_nom;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $pra_prenom;

    /**
     * Compte-rendu de visite
     * 
     * @var collection|rapportVisite[]
     * @ORM\OneToMany(targetEntity="App\Entity\RapportVisite", mappedBy="praticien", cascade={"remove"} )
     */
    private $rapportVisites;

    /**
     * Lie un praticien a une activite
     * 
     * @var collection|inviter[]
     * @ORM\OneToMany(targetEntity="App\Entity\Inviter", mappedBy="praticien", cascade={"remove"})
     */
    private $inviters;

    public function __construct()
    {
        $this->rapportVisites = new ArrayCollection();
        $this->inviters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPraNom(): ?string
    {
        return $this->pra_nom;
    }

    public function setPraNom(string $pra_nom): self
    {
        $this->pra_nom = $pra_nom;

        return $this;
    }

    public function getPraPrenom(): ?string
    {
        return $this->pra_prenom;
    }

    public function setPraPrenom(string $pra_prenom): self
    {
        $this->pra_prenom = $pra_prenom;

        return $this;
    }

    /**
     * @return Collection|RapportVisite[]
     */
    public function getRapportVisites(): Collection
    {
        return $this->rapportVisites;
    }

    public function addRapportVisite(RapportVisite $rapportVisite): self
    {
        if (!$this->rapportVisites->contains($rapportVisite)) {
            $this->rapportVisites[] = $rapportVisite;
            $rapportVisite->setPraticien($this);
        }

        return $this;
    }

    public function removeRapportVisite(RapportVisite $rapportVisite): self
    {
        if ($this->rapportVisites->contains($rapportVisite)) {
            $this->rapportVisites->removeElement($rapportVisite);
            // set the owning side to null (unless already changed)
            if ($rapportVisite->getPraticien() === $this) {
                $rapportVisite->setPraticien(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Inviter[]
     */
    public function getInviters(): Collection
    {
        return $this->inviters;
    }

    public function addInviter(Inviter $inviter): self
    {
        if (!$this->inviters->contains($inviter)) {
            $this->inviters[] = $inviter;
            $inviter->setPraticien($this);
        }

        return $this;
    }

    public function removeInviter(Inviter $inviter): self
    {
        if ($this->inviters->contains($inviter)) {
            $this->inviters->removeElement($inviter);
            // set the owning side to null (unless already changed)
            if ($inviter->getPraticien() === $this) {
                $inviter->setPraticien(null);
            }
        }

        return $this;
    }

    public function __ToString(): string
    {
            return $this->pra_prenom . " " . $this->pra_nom;
    }
}

gestionRapportVisites/src/Entity/RapportVisite.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * Compte-rendu de la visite
 * 
 * @ORM\Entity(repositoryClass="App\Repository\RapportVisiteRepository")
 */
class RapportVisite
{
    /**
     * @Groups({"group1"})
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Groups({"group1"})
     * @var date 
     * @ORM\Column(type="date")
     */
    private $rap_date;

    /**
     * Bilan du rapport
     * 
     * @Groups({"group1"})
     * @var string
     * @ORM\Column(type="text")
     */
    private $rap_bilan;

    /**
     * @Groups({"group1"})
     * Motif du rapport
     * 
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $rap_motif;

    /**
     * Visiteur ayant effectué la visite
     * 
     * @var visiteur
     * @ORM\ManyToOne(targetEntity="App\Entity\Visiteur", inversedBy="rapportVisites")
     * @ORM\JoinColumn(nullable=false)
     */
    private $visiteur;

    /**
     * Praticien concerne par la visite
     * 
     * @var praticien
     * @ORM\ManyToOne(targetEntity="App\Entity\Praticien", inversedBy="rapportVisites")
     * @ORM\JoinColumn(nullable=false)
     */
    private $praticien;

    /**
     * Reference un medicament et sa quantite offerte a un praticien lors d'une visite
     * 
     * @var collection|offrir[]
     * @ORM\OneToMany(targetEntity="App\Entity\Offrir", mappedBy="rapportVisite", orphanRemoval=true, cascade={"persist"})
     */
    private $offrirs;

    public function __construct()
    {
        $this->offrirs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRapDate(): ?\DateTimeInterface
    {
        return $this->rap_date;
    }

    public function setRapDate(\DateTimeInterface $rap_date): self
    {
        $this->rap_date = $rap_date;

        return $this;
    }

    public function getRapbilan(): ?string
    {
        return $this->rap_bilan;
    }

    public function setRapbilan(string $rap_bilan): self
    {
        $this->rap_bilan = $rap_bilan;

        return $this;
    }

    public function getRapMotif(): ?string
    {
        return $this->rap_motif;
    }

    public function setRapMotif(string $rap_motif): self
    {
        $this->rap_motif = $rap_motif;

        return $this;
    }

    public function getVisiteur(): ?Visiteur
    {
        return $this->visiteur;
    }

    public function setVisiteur(?Visiteur $visiteur): self
    {
        $this->visiteur = $visiteur;

        return $this;
    }

    public function getPraticien(): ?Praticien
    {
        return $this->praticien;
    }

    public function setPraticien(?Praticien $praticien): self
    {
        $this->praticien = $praticien;

        return $this;
    }

    /**
     * @return Collection|Offrir[]
     */
    public function getOffrirs(): Collection
    {
        return $this->offrirs;
    }

    public function addOffrir(Offrir $offrir): self
    {
        if (!$this->offrirs->contains($offrir)) {
            $this->offrirs[] = $offrir;
            $offrir->setRapportVisite($this);
        }

        return $this;
    }

    public function removeOffrir(Offrir $offrir): self
    {
        if ($this->offrirs->contains($offrir)) {
            $this->offrirs->removeElement($offrir);
            // set the owning side to null (unless already changed)
            if ($offrir->getRapportVisite() === $this) {
                $offrir->setRapportVisite(null);
            }
        }

        return $this;
    }

}

gestionRapportVisites/src/Entity/Visiteur.php
<?php

namespace App\Entity;

use App\Entity\Visiteur;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VisiteurRepository")
 */
class Visiteur
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $vis_nom;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $vis_prenom;

    /**
     * Rapport rédigé
     * 
     * @var collection|rapportVisite[]
     * @ORM\OneToMany(targetEntity="App\Entity\RapportVisite", mappedBy="visiteur")
     */
    private $rapportVisites;

    /**
     * Acitivite(s) que le visiteur a organise
     * 
     * @var collection|activiteCompl[]
     * @ORM\ManyToMany(targetEntity="App\Entity\ActiviteCompl", mappedBy="visiteur")
     */
    private $activiteCompls;

    public function __construct()
    {
        $this->rapportVisites = new ArrayCollection();
        $this->activiteCompls = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVisNom(): ?string
    {
        return $this->vis_nom;
    }

    public function setVisNom(string $vis_nom): self
    {
        $this->vis_nom = $vis_nom;

        return $this;
    }

    public function getVisPrenom(): ?string
    {
        return $this->vis_prenom;
    }

    public function setVisPrenom(string $vis_prenom): self
    {
        $this->vis_prenom = $vis_prenom;

        return $this;
    }

    /**
     * @return Collection|RapportVisite[]
     */
    public function getRapportVisites(): Collection
    {
        return $this->rapportVisites;
    }

    public function addRapportVisite(RapportVisite $rapportVisite): self
    {
        if (!$this->rapportVisites->contains($rapportVisite)) {
            $this->rapportVisites[] = $rapportVisite;
            $rapportVisite->setVisiteur($this);
        }

        return $this;
    }

    public function removeRapportVisite(RapportVisite $rapportVisite): self
    {
        if ($this->rapportVisites->contains($rapportVisite)) {
            $this->rapportVisites->removeElement($rapportVisite);
            // set the owning side to null (unless already changed)
            if ($rapportVisite->getVisiteur() === $this) {
                $rapportVisite->setVisiteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ActiviteCompl[]
     */
    public function getActiviteCompls(): Collection
    {
        return $this->activiteCompls;
    }

    public function addActiviteCompl(ActiviteCompl $activiteCompl): self
    {
        if (!$this->activiteCompls->contains($activiteCompl)) {
            $this->activiteCompls[] = $activiteCompl;
            $activiteCompl->addVisiteur($this);
        }

        return $this;
    }

    public function removeActiviteCompl(ActiviteCompl $activiteCompl): self
    {
        if ($this->activiteCompls->contains($activiteCompl)) {
            $this->activiteCompls->removeElement($activiteCompl);
            $activiteCompl->removeVisiteur($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->vis_nom . " " . $this->vis_prenom;
    }
}

gestionRapportVisites/src/Controller/ApplicationRapportController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Offrir;
use App\Entity\RapportVisite;
use App\Form\RapportVisiteType;
use App\Repository\RapportVisiteRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ApplicationRapportController extends AbstractController
{


    /**
     * Visiblement, pas l'index
     * 
     * @Route("/", name="home")
     */
    public function index()
    {
        return $this->render('application_rapport/index.html.twig', [
            'controller_name' => 'ApplicationRapportController',
        ]);
    }

    /**
     * Index
     * 
     * @Route("/liste_rapport", name="listerapport")
     */
    public function Rapports(RapportVisiteRepository $repo,Request $request, ObjectManager $manager){

        $form = $this->createFormBuilder(array('message' => 'search'))
        ->add('search', TextType::class, [
            'attr' => [
                'class' => 'input is-hovered',
                'placeholder' => 'Rechercher par titre ou praticien'
            ],
            'label' => false,
            'required' => false
        ])
        ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            return $this->render('application_rapport/listerapport.html.twig', [
                'controller_name' => 'ApplicationRapportController',
                'rapports' =>  $repo->findManyByText($data['search']),
                'sForm' => $form->createView(),
            ]);
        }

        return $this->render('application_rapport/listerapport.html.twig', [
            'rapports' => $repo->findAll(),
            'sForm' => $form->createView(),
        ]);

    }

    /**
     * Montre un rapport détaillé
     *
     * @Route("/rapport/{id}", name="showRapport")
     * 
     * @return void
     */
    public function showRapport(RapportVisiteRepository $repo, $id)
    {
        return $this->render('application_rapport/showRapport.html.twig', [
            'rapport' => $repo->find($id),
        ]);
    }

    /**
     * Creation / Edition d'un rapport 
     * 
     * @Route("/create", name="ajoutrapport")
     * @route("/{id}/edit",  name="modifrapport")
     */
    public function form(RapportVisite $rapport=null, Request $request, ObjectManager $manager){
        if (!$rapport) {
            $rapport = new RapportVisite();

            $offrir1 = new Offrir();
            $offrir2 = new Offrir();
            $offrir3 = new Offrir();
            
            $rapport->addOffrir($offrir1);
            $rapport->addOffrir($offrir2);
            $rapport->addOffrir($offrir3);
        }
        $form = $this->createForm(RapportVisiteType::class, $rapport);
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rapport->setRapDate(new DateTime());
            dump($rapport);
            foreach($rapport->getOffrirs() as $offrir)
            {
                if(!$offrir->getOffQte())
                {
                    $rapport->removeOffrir($offrir);
                }
                else
                {
                    $manager->persist($offrir);
                }
            }
            // $rapport->setVisiteur($this->getUser());
            dump($rapport);
            $manager->persist($rapport);
            $manager->flush();

            return $this->redirectToRoute('listerapport');
        }

        return $this->render('application_rapport/create.html.twig',[
            'formRapportVisite' => $form->createView(),
            'editMode' => $rapport->getId()!== null
        ]);
    }

    /**
     * Suppression d'un rapport
     * 
     * @Route("/{id}/supprimer", name="removerapport")
     */
    public function remove(RapportVisiteRepository $repo, $id, ObjectManager $manager)
    {
        $rapport = $repo->find($id);
        dump($rapport);
        $manager->remove($rapport);
        $manager->flush();

        return $this->redirectToRoute('listerapport');
    }


}

gestionRapportVisites/templates/application_rapport/create.html.twig
{% extends 'base.html.twig' %}

{% import _self as renderJobMacro %}
{% macro offrirs(offrir) %}
<li>
    <div class="columns">
        <div class="column is-3">
            <div>
                {{ form_label(offrir.medicament) }}
            </div>
            <div class="select">
                {{ form_widget(offrir.medicament) }}
            </div>
        </div>
        <div class="column">
            <div>
                {{ form_label(offrir.off_qte) }}
            </div>
            <div class="control">
                {{ form_widget(offrir.off_qte) }}
            </div>
        </div>
        <div class="column delete_medic">
        <br>
        </div>
    </div>
</li>
{% endmacro %}

{% block title %}Liste medicaments{% endblock %}

{% block body %}
<div class="fondgris">
    <div class="container corpformrap">

        <div class="columns">
            <div class="column is-2"></div>
            <div class="column">

                <div class="box">
                    <div class="margform">
                        <h1 class="title is-3 has-text-dark margform">
                            {% if editMode == true %}
                            Modifier
                            {% else %}
                            Ajouter
                            {% endif %}
                            un rapport de visite</h1>
                        <h1 class="subtitle is-5 has-text-dark margform">----------------------------</h1>
                        {{ form_start(formRapportVisite) }}
                        <div class="columns">
                            <div class="column is-6">
                                <div>
                                    {{ form_label(formRapportVisite.praticien) }}
                                </div>
                                <div class="select">
                                    {{ form_widget(formRapportVisite.praticien) }}
                                </div>
                            </div>
                            <div class="column is-6">
                                <div>
                                    {{ form_label(formRapportVisite.visiteur) }}
                                </div>
                                <div class="select">
                                    {{ form_widget(formRapportVisite.visiteur )}}
                                </div>
                            </div>
                        </div>
                        {{ form_row(formRapportVisite.rap_motif) }}
                        <br>
                        {{ form_row(formRapportVisite.rap_bilan) }}
                        <br>
                        <ul class="offrir" data-prototype="{{ renderJobMacro.offrirs(formRapportVisite.offrirs.vars.prototype)|e }}">
                            {% for offrir in formRapportVisite.offrirs %}
                            {{ renderJobMacro.offrirs(offrir)}}
                            {% endfor %}
                        </ul>

                        <div>
                            <button type="submit" class="button is-primary" style="margin-top:4%">
                                {% if editMode == true %}
                                Enregistrer les modifications
                                {% else %}
                                Poster le rapport
                                {% endif %}
                            </button>
                        </div>

                        {{ form_end(formRapportVisite) }}
                    </div>
                </div>
            </div>
            <div class="column is-2"></div>
        </div>

    </div>
</div>
{% endblock %}

{% block javascripts %}
<script>
    var $collectionHolder;

    var $addTagButton = $(
        '<button type="button" class="add_tag_link button is-link is-small" style="margin-bot:4%"><i class="fas fa-plus"></i>Ajouter un medicament</button>'
    );
    var $newLinkLi = $('<li></li>').append($addTagButton);

    jQuery(document).ready(function () {
        // Get the ul that holds the collection of offrir
        $collectionHolder = $('ul.offrir');

        // add a delete link to all of the existing tag form li elements
        $collectionHolder.find('li').each(function() {
            addTagFormDeleteLink($(this));
        });

        // add the "ajouter un medicament" anchor and li to the tags ul
        $collectionHolder.prepend($newLinkLi);

        // count the current form inputs we have (e.g. 2), use that as the new
        // index when inserting a new item (e.g. 2)
        $collectionHolder.data('index', $collectionHolder.find(':input').length);

        $addTagButton.on('click', function (e) {
            // add a new medicament form (see next code block)
            addTagForm($collectionHolder, $newLinkLi);
        });
    });

    function addTagForm($collectionHolder, $newLinkLi) {
        // Get the data-prototype 
        var prototype = $collectionHolder.data('prototype');

        // get the new index
        var index = $collectionHolder.data('index');

        var newForm = prototype;

        // Replace '__name__' in the prototype's HTML to
        // instead be a number based on how many items we have
        newForm = newForm.replace(/__name__/g, index);

        // increase the index with one for the next item
        $collectionHolder.data('index', index + 1);


        // Display the form in the page in an li, before the "Ajouter un medicament" link li
        var $newFormLi = $('<li></li>').append(newForm);
        addTagFormDeleteLink($newFormLi);
        $newLinkLi.append($newFormLi);
    }

    function addTagFormDeleteLink($tagFormLi) {
    var $removeFormButton = $('<button class="delete is-medium" type="button"></button>');
    $tagFormLi.find('.delete_medic').append($removeFormButton);

    $removeFormButton.on('click', function(e) {
        // remove the li for the medicament form
        $tagFormLi.remove();
    });
}
</script>
{% endblock %}

gestionRapportVisites/templates/application_rapport/listerapport.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste rapports{% endblock %}

{% block body %}
<div class="fondgris">
    <div class="container corp">

        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column">
                <a href=""><h1 class="title is-3 has-text-white">Liste des rapports de visite</h1></a>
                <h1 class="subtitle is-5 has-text-white">----------------------------</h1>
            </div>
            <div class="column is-1">
            </div>
        </div>

        <div class="columns">
        <div class="column is-1">
        </div>
        <div class="column is-3">
        <a class="button is-primary" href="{{ path("ajoutrapport") }}">
            
                    <span class="icon">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span>
                        Ajouter un rapport
                    </span>
        </a>
        </div>
            <div class="column is-3 is-offset-3">
                
            {{ form_start(sForm) }}
            {{ form_row(sForm.search) }}
                
            </div>
            <div class="column is-1">
                <button type="submit" class="button is-primary"><i class="fas fa-search"></i></button>
                {{ form_end(sForm) }}
            </div>

        <div class="column is-1">
        </div>
        </div>

        {% for rapport in rapports %}
        <br><br>

                <div class="columns">
                <div class="column is-1">
                </div>
                <div class="column">
        <div class="box">
            <article class="media">



                <div class="media-content">
                    <div class="content">
                        <p>
                            <h4 class="title is-4"></p><strong>{{ rapport.id }}. {{ rapport.rapMotif }}</strong></h4>
                            <h6 class="subtitle is-6">Date d'ajout : {{ rapport.RapDate | date('d/m/Y à H:i') }}</h6>
                            Praticien : {{ rapport.praticien.praNom }} {{ rapport.praticien.praPrenom }}
                            <br>Visiteur : {{ rapport.visiteur.visNom }} {{ rapport.visiteur.visPrenom }}
                            <br><br> <a href="{{ path('showRapport', { 'id' : rapport.id }) }}">Voir plus</a>
                        </p>
                    </div>
                    <nav class="level is-mobile">
                        <div class="level-left">
                            <a class="level-item" aria-label="modifier" href="{{ path('modifrapport', {'id':rapport.id}) }}">
                                <span class="icon is-small">
                                    <i class="fas fa-wrench"></i>
                                </span>
                            </a>
                            <a class="level-item" aria-label="supprimer" href="{{ path('removerapport', {'id':rapport.id}) }}" onclick="return confirm('Êtes-vous sûr ?')">
                                <span class="icon is-small">
                                    <i class="fas fa-times"></i>
                                </span>
                            </a>
                        </div>
                    </nav>
                </div>
            </article>
        </div>
                </div>
                <div class="column is-1">
                </div>
                </div>
                <br>

        {% endfor %}

    </div>
    </div>
{% endblock %}

gestionRapportVisites/templates/application_rapport/showRapport.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste rapports{% endblock %}

{% block body %}
<div class="fondgris">
    <div class="container corp">

        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column">
                <a href="">
                    <h1 class="title is-3 has-text-white">Détail rapport visite</h1>
                </a>
                <h1 class="subtitle is-5 has-text-white">----------------------------</h1>
            </div>
            <div class="column is-1">
            </div>
        </div>

        <br><br>

        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column">
                <div class="box">
                    <article class="media">



                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <h4 class="title is-4">
                                </p><strong>{{ rapport.id }}. {{ rapport.rapMotif }}</strong></h4>
                                <h6 class="subtitle is-6">Date d'ajout : {{ rapport.RapDate | date('d/m/Y') }}</h6>
                                <br>
                                {{ rapport.rapBilan }}
                                <br>
                                {% if rapport.offrirs is empty %}
                                <br><b>Aucun</b> médicament offert au cours de la visite.<br>
                                
                                {% else %}
                                <h1 class="title is-6">Liste des medicaments offerts:</h1>
                                <table>
                                    <tr>
                                        <th>Libelle : </th>
                                        <th>Quantitée :</th>
                                    </tr>
                                    {% for offrir in rapport.offrirs %}
                                    <tr>
                                        <td>{{ offrir.medicament.libelle }}</td>
                                        <td>{{ offrir.offQte }}</td>
                                    </tr>
                                    {% endfor %}
                                </table>
                                {% endif %}
                                <br>Praticien : {{ rapport.praticien.praNom }} {{ rapport.praticien.praPrenom }}
                                <br>Visiteur : {{ rapport.visiteur.visNom }} {{ rapport.visiteur.visPrenom }}

                                </p>
                            </div>
                            <nav class="level is-mobile">
                                <div class="level-left">
                                    <a class="level-item" aria-label="modifier" href="{{ path('modifrapport', {'id':rapport.id}) }}">
                                        <span class="icon is-small">
                                            <i class="fas fa-wrench"></i>
                                        </span>
                                    </a>
                                    <a class="level-item" aria-label="suprimer" href="{{ path('removerapport', {'id':rapport.id}) }}" onclick="
                                        return confirm('Êtes-vous sûr ?')">
                                        <span class="icon is-small">
                                            <i class="fas fa-times"></i>
                                        </span>
                                    </a>
                                </div>
                            </nav>
                        </div>
                    </article>
                </div>
            </div>
            <div class="column is-1">
            </div>
        </div>
        <br>

    </div>
</div>
{% endblock %}