gestionRapportVisites/src/Entity/ActiviteCompl.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Activite complementaire, gerer par un/ des visiteur(s) a destination des praticiens
 * 
 * @ORM\Entity(repositoryClass="App\Repository\ActiviteComplRepository")
 */
class ActiviteCompl
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Date de l'activite 
     * 
     * @var date
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * Lieu de l'activite 
     * 
     * @var string 
     * @ORM\Column(type="string", length=255)
     */
    private $lieu;

    /**
     * Theme de l'activite 
     * 
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $theme;

    /**
     * Visiteur, organisateur de l'activite
     * 
     * @var visiteur
     * @ORM\ManyToMany(targetEntity="App\Entity\Visiteur", inversedBy="activiteCompls")
     */
    private $visiteur;

    /**
     * Objet invitation, liant un praticien a une activite 
     * 
     * @var collection|inviter[]
     * @ORM\OneToMany(targetEntity="App\Entity\Inviter", mappedBy="activiteCompl", orphanRemoval=true)
     */
    private $inviters;

    /**
     * @var string Fournir un URL
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    public function __construct()
    {
        $this->visiteur = new ArrayCollection();
        $this->inviters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(string $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    /**
     * @return Collection|Visiteur[]
     */
    public function getVisiteur(): Collection
    {
        return $this->visiteur;
    }

    public function addVisiteur(Visiteur $visiteur): self
    {
        if (!$this->visiteur->contains($visiteur)) {
            $this->visiteur[] = $visiteur;
        }

        return $this;
    }

    public function removeVisiteur(Visiteur $visiteur): self
    {
        if ($this->visiteur->contains($visiteur)) {
            $this->visiteur->removeElement($visiteur);
        }

        return $this;
    }

    /**
     * @return Collection|Inviter[]
     */
    public function getInviters(): Collection
    {
        return $this->inviters;
    }

    public function addInviter(Inviter $inviter): self
    {
        if (!$this->inviters->contains($inviter)) {
            $this->inviters[] = $inviter;
            $inviter->setActiviteCompl($this);
        }

        return $this;
    }

    public function removeInviter(Inviter $inviter): self
    {
        if ($this->inviters->contains($inviter)) {
            $this->inviters->removeElement($inviter);
            // set the owning side to null (unless already changed)
            if ($inviter->getActiviteCompl() === $this) {
                $inviter->setActiviteCompl(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }
}

gestionRapportVisites/src/Entity/Praticien.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PraticienRepository")
 */
class Praticien
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $pra_nom;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $pra_prenom;

    /**
     * Compte-rendu de visite
     * 
     * @var collection|rapportVisite[]
     * @ORM\OneToMany(targetEntity="App\Entity\RapportVisite", mappedBy="praticien", cascade={"remove"} )
     */
    private $rapportVisites;

    /**
     * Lie un praticien a une activite
     * 
     * @var collection|inviter[]
     * @ORM\OneToMany(targetEntity="App\Entity\Inviter", mappedBy="praticien", cascade={"remove"})
     */
    private $inviters;

    public function __construct()
    {
        $this->rapportVisites = new ArrayCollection();
        $this->inviters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPraNom(): ?string
    {
        return $this->pra_nom;
    }

    public function setPraNom(string $pra_nom): self
    {
        $this->pra_nom = $pra_nom;

        return $this;
    }

    public function getPraPrenom(): ?string
    {
        return $this->pra_prenom;
    }

    public function setPraPrenom(string $pra_prenom): self
    {
        $this->pra_prenom = $pra_prenom;

        return $this;
    }

    /**
     * @return Collection|RapportVisite[]
     */
    public function getRapportVisites(): Collection
    {
        return $this->rapportVisites;
    }

    public function addRapportVisite(RapportVisite $rapportVisite): self
    {
        if (!$this->rapportVisites->contains($rapportVisite)) {
            $this->rapportVisites[] = $rapportVisite;
            $rapportVisite->setPraticien($this);
        }

        return $this;
    }

    public function removeRapportVisite(RapportVisite $rapportVisite): self
    {
        if ($this->rapportVisites->contains($rapportVisite)) {
            $this->rapportVisites->removeElement($rapportVisite);
            // set the owning side to null (unless already changed)
            if ($rapportVisite->getPraticien() === $this) {
                $rapportVisite->setPraticien(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Inviter[]
     */
    public function getInviters(): Collection
    {
        return $this->inviters;
    }

    public function addInviter(Inviter $inviter): self
    {
        if (!$this->inviters->contains($inviter)) {
            $this->inviters[] = $inviter;
            $inviter->setPraticien($this);
        }

        return $this;
    }

    public function removeInviter(Inviter $inviter): self
    {
        if ($this->inviters->contains($inviter)) {
            $this->inviters->removeElement($inviter);
            // set the owning side to null (unless already changed)
            if ($inviter->getPraticien() === $this) {
                $inviter->setPraticien(null);
            }
        }

        return $this;
    }

    public function __ToString(): string
    {
            return $this->pra_prenom . " " . $this->pra_nom;
    }
}

gestionRapportVisites/src/Entity/Visiteur.php
<?php

namespace App\Entity;

use App\Entity\Visiteur;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VisiteurRepository")
 */
class Visiteur
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $vis_nom;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $vis_prenom;

    /**
     * Rapport rédigé
     * 
     * @var collection|rapportVisite[]
     * @ORM\OneToMany(targetEntity="App\Entity\RapportVisite", mappedBy="visiteur")
     */
    private $rapportVisites;

    /**
     * Acitivite(s) que le visiteur a organise
     * 
     * @var collection|activiteCompl[]
     * @ORM\ManyToMany(targetEntity="App\Entity\ActiviteCompl", mappedBy="visiteur")
     */
    private $activiteCompls;

    public function __construct()
    {
        $this->rapportVisites = new ArrayCollection();
        $this->activiteCompls = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVisNom(): ?string
    {
        return $this->vis_nom;
    }

    public function setVisNom(string $vis_nom): self
    {
        $this->vis_nom = $vis_nom;

        return $this;
    }

    public function getVisPrenom(): ?string
    {
        return $this->vis_prenom;
    }

    public function setVisPrenom(string $vis_prenom): self
    {
        $this->vis_prenom = $vis_prenom;

        return $this;
    }

    /**
     * @return Collection|RapportVisite[]
     */
    public function getRapportVisites(): Collection
    {
        return $this->rapportVisites;
    }

    public function addRapportVisite(RapportVisite $rapportVisite): self
    {
        if (!$this->rapportVisites->contains($rapportVisite)) {
            $this->rapportVisites[] = $rapportVisite;
            $rapportVisite->setVisiteur($this);
        }

        return $this;
    }

    public function removeRapportVisite(RapportVisite $rapportVisite): self
    {
        if ($this->rapportVisites->contains($rapportVisite)) {
            $this->rapportVisites->removeElement($rapportVisite);
            // set the owning side to null (unless already changed)
            if ($rapportVisite->getVisiteur() === $this) {
                $rapportVisite->setVisiteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ActiviteCompl[]
     */
    public function getActiviteCompls(): Collection
    {
        return $this->activiteCompls;
    }

    public function addActiviteCompl(ActiviteCompl $activiteCompl): self
    {
        if (!$this->activiteCompls->contains($activiteCompl)) {
            $this->activiteCompls[] = $activiteCompl;
            $activiteCompl->addVisiteur($this);
        }

        return $this;
    }

    public function removeActiviteCompl(ActiviteCompl $activiteCompl): self
    {
        if ($this->activiteCompls->contains($activiteCompl)) {
            $this->activiteCompls->removeElement($activiteCompl);
            $activiteCompl->removeVisiteur($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->vis_nom . " " . $this->vis_prenom;
    }
}

gestionRapportVisites/src/Controller/ActvtComplController.php
<?php

namespace App\Controller;

use \App\Entity\Inviter;
use App\Entity\Visiteur;
use App\Entity\Praticien;
use App\Form\InviterType;
use App\Entity\ActiviteCompl;
use App\Form\ActiviteComplType;
use App\Repository\InviterRepository;
use App\Repository\VisiteurRepository;
use App\Repository\ActiviteComplRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ActvtComplController extends AbstractController
{
    /**
     * @Route("/activite-complementaire", name="actvt_compl")
     */
    public function index(Request $request, ActiviteComplRepository $repo)
    {
        $form = $this->CreateFormBuilder()
        ->add('search', TextType::class, [
            'attr' => [
                'class' => 'input is-hovered',
                'placeholder' => 'Rechercher'
            ],
            'label' => false,
            'required' => false
        ])
        ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            return $this->render('actvt_compl/index.html.twig', [
                'activites' =>  $repo->findManyByText($data['search']),
                'searchForm' => $form->CreateView(),
            ]);
        }
        return $this->render('actvt_compl/index.html.twig', [
            'activites' => $repo->findAll(),
            'searchForm' => $form->CreateView()
        ]);
        
    }

    /**
     * Montre le detail d'une activite pour un ID
     * 
     * @Route("/activite-complementaire/{id}", name="showActivite")
     */
    public function show(ActiviteComplRepository $repo, $id)
    {
        $activite = $repo->findBy(['id' => $id])[0];
        return $this->render('actvt_compl/showActivite.html.twig', [
            'activite' => $activite,
            'visiteurs' => $activite->getVisiteur(),
            'invitation' => $activite->getInviters()

        ]);
    }

    /**
     * Invite un praticien à une activite
     * 
     * @Route("/inviter-praticien/{id}", name="inviterPraticien")
     */
    public function inviterPraticien(Request $request, ObjectManager $manager, $id, ActiviteComplRepository $repo)
    {
        $inviter = new Inviter();

        $form = $this->CreateForm(InviterType::class, $inviter);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $inviter->setActiviteCompl($repo->find($id));
            $manager->persist($inviter);
            $manager->flush();

            return $this->redirectToRoute('showActivite',[ "id" => $id]);
        }

        return $this->render('actvt_compl/Invitationform.html.twig', [
            'form' => $form->CreateView()
        ]);
    }

    /**
     * Supprime un praticien de l'activite
     * 
     * @Route("/supprimer-invitation/{id}", name="removeInviter")
     */
    public function removeInviter($id, ObjectManager $manager, InviterRepository $repo)
    {
        $invitation = $repo->find($id);
        $manager->remove($invitation);
        $manager->flush();

        return $this->redirectToRoute("showActivite", [ "id" => $invitation->getActiviteCompl()->getId()]);
    }

    /**
     * Ajoute un visiteur a une activite
     * 
     * @Route("/ajouter-organisateur/{id}", name="ajouterVisiteur")
     */
    public function ajouterOrganisateur(ObjectManager $manager, Request $request, $id, ActiviteComplRepository $repo)
    {
        $activite = $repo->find($id);

        
        $form = $this->CreateFormBuilder()
                     ->add('visiteur', EntityType::class, [
                         'class' => Visiteur::class,
                     ])->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $visiteur = $form->getData()['visiteur'];
            $activite->addVisiteur($visiteur);
            $manager->persist($activite);
            $manager->flush();

            return $this->redirectToRoute("showActivite", [ "id" => $activite->getId()]);
        }

        return $this->render('actvt_compl/VisiteurForm.html.twig', [
            'form' => $form->CreateView(),
        ]);
    }

    /**
     * Supprime un visiteur de l'activite 
     * 
     * @Route("/activite-complementaire/{idActivite}/supprimer-organisateur/{idOrganisateur}", name="removeOrganisateur")
     */
    public function removeOrganisateur($idActivite, $idOrganisateur,ObjectManager $manager, VisiteurRepository $repoVisiteur, Request $request, ActiviteComplRepository $repoActivite)
    {
        $visiteur = $repoVisiteur->find($idOrganisateur);
        $activite = $repoActivite->find($idActivite);
        $activite->removeVisiteur($visiteur);
        $manager->persist($activite);
        $manager->flush();

        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * Formulaire d'ajout / modification d'une activite
     * 
     * @Route("/modifier-activite-complementaire/{id}", name="modifierActivite")
     * @Route("/ajouter-activite-complementaire/", name="ajouterActivite")
     */
    public function formEvenement(ActiviteCompl $activite = null, $ajout=false, ObjectManager $manager, Request $request)
    {
        if(!$activite)
        {
            $activite = new ActiviteCompl();
            $ajout = true;  //Si = true, le contact est ajouté et non modifié
        }

        $form = $this->createForm(ActiviteComplType::class, $activite); //Création du form

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $manager->persist($activite);
            $manager->flush();

           
            return $this->redirectToRoute('actvt_compl');
        }

        return $this->render('actvt_compl/ActiviteForm.html.twig', [
            'form' => $form->CreateView(),
            'ajout' => $ajout
        ]);
    }

    /**
     * Suppression d'une activite
     * 
     * @Route("/supprimer-activite-complementaire/{id}", name="supprimerActivite")
     */
    public function removeActivite($id, ActiviteComplRepository $repo, ObjectManager $manager)
    {
        $manager->remove($repo->find($id));
        $manager->flush();

        return $this->redirectToRoute('actvt_compl');
    }
}

gestionRapportVisites/templates/actvt_compl/ActiviteForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulaire Activite{% endblock %}

{% block body %}
<div class="fondgris">
    <div class="container corp">
        <h1 class="title is-3 has-text-white">{% if ajout == true %}Ajouter{% else %}Modifier{% endif %} un praticien</h1>
        <h1 class="subtitle is-5 has-text-white">----------------------------</h1>

        <div class="box">
            {{ form_start(form) }}
            {{ form_row(form.date) }}
            {{ form_row(form.lieu) }}
            {{ form_row(form.theme) }}
            {{ form_row(form.nom) }}
            <button type="submit" class="button is-primary" style="margin-top:6%;">{% if ajout == true %}Ajouter{% else
                %}Modifier{% endif %}</button>
            {{ form_end(form) }}
        </div>
    </div>
</div>
{% endblock %}

gestionRapportVisites/templates/actvt_compl/Invitationform.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invitation{% endblock %}

{% block body %}
<div class="fondgris">
    <div class="container corp">
        <h1 class="title is-3 has-text-white">Inviter un praticien</h1>
        <h1 class="subtitle is-5 has-text-white">----------------------------</h1>

        <div class="box">
            {{ form_start(form) }}
            {{ form_row(form.praticien) }}
            {{ form_row(form.specialisation) }}
            <button type="submit" class="button is-primary" style="margin-top:6%;">Inviter</button>
            {{ form_end(form) }}
        </div>
    </div>
</div>

{% endblock %}

gestionRapportVisites/templates/actvt_compl/VisiteurForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout organisateur{% endblock %}

{% block body %}
<div class="fondgris">
    <div class="container corp">
        <h1 class="title is-3 has-text-white">Ajouter un organisateur</h1>
        <h1 class="subtitle is-5 has-text-white">----------------------------</h1>

        <div class="box">
            {{ form_start(form) }}
            {{ form_row(form.visiteur) }}
            <button type="submit" class="button is-primary" style="margin-top:6%;">Inviter</button>
            {{ form_end(form) }}
        </div>
    </div>
</div>

{% endblock %}

gestionRapportVisites/templates/actvt_compl/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Activité Complémentaire{% endblock %}

{% block body %}
<div class="fondgris">
    <div class="container corp">
        <div class="columns">
            <div class="column is-1"></div>
            <div class="column">
                <a href="">
                    <h1 class="title is-3 has-text-white">Liste des activités complémentaires prévues</h1>
                </a>
                <h1 class="subtitle is-5 has-text-white">----------------------------</h1>
            </div>
            <div class="column is-1"></div>
        </div>

        <div class="columns">
            <div class="column is-1"></div>
            <div class="column is-3">
                <a href="{{ path("ajouterActivite") }}" class="button is-primary">
                    <span class="icon">
                        <i class="fas fa-plus"></i>
                    </span><span>Ajouter évènement</span></a>
            </div>
            <div class="column is-3 is-offset-3">

                {{ form_start(searchForm) }}
                {{ form_row(searchForm.search) }}

            </div>
            <div class="column is-1">
                <button type="submit" class="button is-primary">
                    <i class="fas fa-search"></i>
                </button>
                {{ form_end(searchForm) }}
            </div>
            <div class="column is-1"></div>
        </div>
        <br><br>
        <div class="columns is-multiline">
            {# <div class="column is-1"></div> #}
            {% for activite in activites %}

            <div class="column is-3">
                <div class="box">
                    <article class="media">
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <strong>Activité n°
                                        {{ activite.id }}</strong>
                                    <br>
                                    Date :
                                    {{ activite.date | date("d/m/Y")}}
                                    <br>
                                    Lieu :
                                    {{ activite.lieu }}
                                    <br>
                                    Theme :
                                    {{ activite.theme }}
                                    <br>
                                    <a href=" {{ path("showActivite", { "id" : activite.id } ) }}">Voir plus</a>
                                </p>
                            </div>
                            <nav class="level is-mobile">
                                <div class="level-left">
                                    <a href="{{ path("modifierActivite", {"id" : activite.id }) }}" class="level-item" aria-label="Modifier">
                                        <span class="icon is-small">
                                            <i class="fas fa-wrench"></i>
                                        </span>
                                    </a>
                                    <a href="{{ path("supprimerActivite", {"id" : activite.id }) }}" class="level-item" aria-label="Suprimer" onclick="return confirm('Êtes-vous sûr ?')">
                                        <span class="icon is-small">
                                            <i class="fas fa-times"></i>
                                        </span>
                                    </a>
                                </div>
                            </nav>
                        </div>
                    </article>
                </div>
            </div>
            {% endfor %}
            {# <div class="column is-1"></div> #}
        </div>

    </div>
</div>
{% endblock %}

gestionRapportVisites/templates/actvt_compl/showActivite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activité{% endblock %}

{% block body %}
<div class="fondgris">
    <div class="container corp">
        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column">
                <a href="">
                    <h1 class="title is-3 has-text-white">Activité n° {{ activite.id }}</h1>
                </a>
                <h1 class="subtitle is-5 has-text-white">----------------------------</h1>
            </div>
            <div class="column is-1">
            </div>
        </div>

        <!-- AFFICHAGE ACTIVITE -->

        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column">
                <div class="box">
                    <article class="media">
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    Date : {{ activite.date | date("d/m/Y")}}
                                    <br>
                                    Lieu : {{ activite.lieu }}
                                    <br>
                                    Theme : {{ activite.theme }}
                                </p>
                            </div>
                            <nav class="level is-mobile">
                                <div class="level-left">
                                    <a href="{{ path("modifierActivite", {"id" : activite.id }) }}" class="level-item"
                                        aria-label="Modifier">
                                        <span class="icon is-small">
                                            <i class="fas fa-wrench"></i>
                                        </span>
                                    </a>
                                    <a href="{{ path("supprimerActivite", {"id" : activite.id }) }}" class="level-item"
                                        aria-label="Suprimer" onclick="return confirm('Êtes-vous sûr ?')">
                                        <span class="icon is-small">
                                            <i class="fas fa-times"></i>
                                        </span>
                                    </a>
                                </div>
                            </nav>
                        </div>
                    </article>
                </div>
            </div>
            <div class="column is-1">
            </div>
        </div>

        <!-- AFFICHAGE INVITATION -->

        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column">
                <a href="">
                    <h1 class="title is-3 has-text-white">Invités</h1>
                </a>
                <h1 class="subtitle is-5 has-text-white">----------------------------</h1>
            </div>
            <div class="column is-1">
            </div>
        </div>

        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column is-3">
                <a href="{{ path("inviterPraticien", { "id" : activite.id }) }}" class="button is-primary"><span class="icon"><i
                            class="fas fa-plus"></i></span><span>Inviter un praticien</span></a>
            </div>
        </div>

        {% for invite in invitation %}
        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column">
                <div class="box">
                    <article class="media">
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    Praticien : {{ invite.praticien.praNom }} {{ invite.praticien.praPrenom }}
                                    <br>
                                    Spécialité : {{ invite.specialisation }}
                                </p>
                            </div>
                            <nav class="level is-mobile">
                                <div class="level-left">
                                    <a href="{{ path("removeInviter", {"id" : invite.id }) }}" class="level-item"
                                        aria-label="Supprimer" onclick="return confirm('Êtes-vous sûr ?')">
                                        <span class="icon is-small">
                                            <i class="fas fa-times"></i>
                                        </span>
                                    </a>
                                </div>
                            </nav>
                        </div>
                    </article>
                </div>
            </div>
            <div class="column is-1">
            </div>
        </div>
        <br>
        {% endfor %}

        <!-- AFFICHAGE ORGANISATEUR -->

        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column">
                <a href="">
                    <h1 class="title is-3 has-text-white">Organisateur(s)</h1>
                </a>
                <h1 class="subtitle is-5 has-text-white">----------------------------</h1>
            </div>
            <div class="column is-1">
            </div>
        </div>

        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column is-3">
                <a href="{{ path("ajouterVisiteur", { "id" : activite.id }) }}" class="button is-primary"><span class="icon"><i
                            class="fas fa-plus"></i></span><span>Ajouter un organisateur</span></a>
            </div>
        </div>

        {% for visiteur in visiteurs %}
        <div class="columns">
            <div class="column is-1">
            </div>
            <div class="column">
                <div class="box">
                    <article class="media">
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    {{ visiteur.visNom}} {{ visiteur.visPrenom }}
                                </p>
                            </div>
                            <nav class="level is-mobile">
                                <div class="level-left">
                                    <a href="{{ path("removeOrganisateur", {"idOrganisateur" : visiteur.id, "idActivite" : activite.id }) }}"
                                        class="level-item" aria-label="Supprimer" onclick="return confirm('Êtes-vous sûr ?')">
                                        <span class="icon is-small">
                                            <i class="fas fa-times"></i>
                                        </span>
                                    </a>
                                </div>
                            </nav>
                        </div>
                    </article>
                </div>
            </div>
            <div class="column is-1">
            </div>
        </div>
        <br>
        {% endfor %}

    </div>
</div>

{% endblock %}