gestionRapportVisites/src/Entity/Medicament.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\MedicamentRepository")
 * 
 * @ExclusionPolicy("all")
 * 
 */
class Medicament
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * 
     * @Expose
     */
    private $id;

    /**
     * @var string numero de depot legal
     * @ORM\Column(type="string", length=255)
     * 
     * @Expose
     * @Assert\NotBlank
     */
    private $med_depot_legal;

    /**
     * @var date
     * @ORM\Column(type="date")
     * 
     * @Expose
     */
    private $date_ajout;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     * 
     * @Expose
     * @Assert\NotBlank
     */
    private $libelle;

    /**
     * @var string
     * @ORM\Column(type="text", nullable=true)
     * 
     * @Expose
     */
    private $description;

    /**
     * Objet referancant un medicament et sa quantite offerte a un praticien lors d'une visite
     * 
     * @var collection|offrir[]
     * @ORM\OneToMany(targetEntity="App\Entity\Offrir", mappedBy="medicament")
     * 
     */
    private $offrirs;

    /**
     * @var string fournir un URL
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     * @Expose
     */
    private $image;

    public function __construct()
    {
        $this->offrirs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMedDepotLegal(): ?string
    {
        return $this->med_depot_legal;
    }

    public function setMedDepotLegal(string $med_depot_legal): self
    {
        $this->med_depot_legal = $med_depot_legal;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Offrir[]
     */
    public function getOffrirs(): Collection
    {
        return $this->offrirs;
    }

    public function addOffrir(Offrir $offrir): self
    {
        if (!$this->offrirs->contains($offrir)) {
            $this->offrirs[] = $offrir;
            $offrir->setMedicament($this);
        }

        return $this;
    }

    public function removeOffrir(Offrir $offrir): self
    {
        if ($this->offrirs->contains($offrir)) {
            $this->offrirs->removeElement($offrir);
            // set the owning side to null (unless already changed)
            if ($offrir->getMedicament() === $this) {
                $offrir->setMedicament(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function __toString()
    {
        return $this->libelle;
    }
}

gestionRapportVisites/src/Form/MedicamentType.php
<?php

namespace App\Form;

use App\Entity\Medicament;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class MedicamentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('med_depot_legal', TextType::class,[
                'attr' => [
                    'class' => 'input',
                    'placeholder' => 'Depot legal'
                ],
                'label' => 'Depot legal'
            ])
            // ->add('date_ajout')
            ->add('libelle', TextType::class,[
                'attr' => [
                    'class' => 'input',
                    'placeholder' => 'libelle'
                ],
                'label' => 'Libelle'
            ])
            ->add('description', TextType::class,[
                'attr' => [
                    'class' => 'input',
                    'placeholder' => 'Description'
                ],
                'label' => 'Description'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Medicament::class,
        ]);
    }
}

gestionRapportVisites/src/Controller/Api/MedicamentController.php
<?php

namespace App\Controller\Api;

use App\Entity\Medicament;
use App\Repository\MedicamentRepository;
use App\RepresentationApi\Representation;
// use Symfony\Component\Routing\Annotation\Route;
use App\Exception\ResourceValidationException;
use Doctrine\Common\Persistence\ObjectManager;
// use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use FOS\RestBundle\Controller\Annotations\View;
use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\Request\ParamFetcherInterface;
use FOS\RestBundle\Controller\Annotations as Rest;
use Symfony\Component\Validator\ConstraintViolation;
use Symfony\Component\Validator\ConstraintViolationList;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class MedicamentController extends FOSRestController
{
    /**
     * Retourne une liste de medicaments au format JSON
     * 
     * @Rest\Get("api/medicaments")
     * @Rest\QueryParam(
     *     name="limit",
     *     requirements="\d+",
     *     default="4",
     *     description="Max number of movies per page."
     * )
     * @Rest\QueryParam(
     *     name="offset",
     *     requirements="\d+",
     *     default="1",
     *     description="The pagination offset"
     * )
     * @View()
     * 
     * @param MedicamentRepository $repo
     * @return array
     */
    public function showMedicaments(MedicamentRepository $repo, ParamFetcherInterface $paramFetcher)
    {
        $pager = $repo->search(
            $paramFetcher->get('limit'),
            $paramFetcher->get('offset')
        );
        return new Representation($pager);
    }

    /**
     * Creer un nouveau medicament
     *
     * @Rest\Post("/api/create/medicament")
     * @ParamConverter("medicament", class="App\Entity\Medicament", converter="fos_rest.request_body")
     * @View(StatusCode = 201)
     * 
     * @return void
     */
    public function createMedicament($medicament, ObjectManager $manager, ConstraintViolationList $violations)
    {
        if (count($violations)) {
            $message = 'The JSON sent contains invalid data. Here are the errors you need to correct: ';
            foreach ($violations as $violation) {
                $message .= sprintf("Field %s: %s ", $violation->getPropertyPath(), $violation->getMessage());
            }

            throw new ResourceValidationException($message);
        }
        $manager->persist($medicament);
        $manager->flush();

        return $medicament;
    }
}

gestionRapportVisites/src/Controller/Backend/MedicamentController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Medicament;
use App\Form\MedicamentType;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\MedicamentRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MedicamentController extends AbstractController
{
    /**
     * @Route("/medicament", name="medicament")
     */
    public function index(MedicamentRepository $repo, Request $request)
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
            
        $form->handleRequest($request);
       
        // dump($form->getData());
        if ($form->isSubmitted() && $form->isValid()) {
            // $data = $form->getData();
            $medocs=$repo->findCritere($search->getSearch(), $search->getDateSearch());
            // $medocs=$repo->findManyByText($search->getSearch());
            dump($medocs);
            return $this->render('medicament/index.html.twig', [
                'medicaments' =>  $medocs,
                'searchForm' => $form->createView(),
            ]);
        }
        
        return $this->render('medicament/index.html.twig', [
            'controller_name' => 'MedicamentController',
            'medicaments' => $repo->findAll(),
            'searchForm' => $form->createView(),     
        ]);
    }

    /**
     * Creation / Edition d'un medicament
     * 
     * @Route("/medicament/ajouter", name="ajouterMedicament")
     * @Route("/medicament/{id}/modifier", name="modifierMedicament")
     */
    public function form(Medicament $medicament = null, $ajout=false, ObjectManager $manager, Request $request)
    {
        if(!$medicament)
        {
            $medicament = new Medicament();
            $ajout = true;  //Si = true, le contact est ajouté et non modifié
        }

        $form = $this->createForm(MedicamentType::class, $medicament); //Création du form

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $medicament->setDateAjout(new \DateTime());
            $manager->persist($medicament);
            $manager->flush();

           
            return $this->redirectToRoute('medicament');
        }

        return $this->render('medicament/formMedicament.html.twig', [
            'formMedicament' => $form->createView(),
            'ajout' => $ajout
        ]);
    }

    /**
     * Suppression medicament
     * 
     * @Route("/medicament/{id}/supprimer", name="supprimerMedicament")
     */
    public function remove(MedicamentRepository $repo, $id, ObjectManager $manager)
    {
        $medicament = $repo->find($id);
        $manager->remove($medicament);
        $manager->flush();

        return $this->redirectToRoute('medicament');
    }


}

gestionRapportVisites/src/Controller/MedicamentController.php
<?php

namespace App\Controller;

use App\Entity\Medicament;
use App\Form\MedicamentType;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\MedicamentRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MedicamentController extends AbstractController
{
    /**
     * @Route("/medicament", name="medicament")
     */
    public function index(MedicamentRepository $repo, Request $request)
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
            
        $form->handleRequest($request);
       
        // dump($form->getData());
        if ($form->isSubmitted() && $form->isValid()) {
            // $data = $form->getData();
            $medocs=$repo->findCritere($search->getSearch(), $search->getDateSearch());
            // $medocs=$repo->findManyByText($search->getSearch());
            dump($medocs);
            return $this->render('medicament/index.html.twig', [
                'medicaments' =>  $medocs,
                'searchForm' => $form->createView(),
            ]);
        }
        
        return $this->render('medicament/index.html.twig', [
            'controller_name' => 'MedicamentController',
            'medicaments' => $repo->findAll(),
            'searchForm' => $form->createView(),     
        ]);
    }

    /**
     * Creation / Edition d'un medicament
     * 
     * @Route("/medicament/ajouter", name="ajouterMedicament")
     * @Route("/medicament/{id}/modifier", name="modifierMedicament")
     */
    public function form(Medicament $medicament = null, $ajout=false, ObjectManager $manager, Request $request)
    {
        if(!$medicament)
        {
            $medicament = new Medicament();
            $ajout = true;  //Si = true, le contact est ajouté et non modifié
        }

        $form = $this->createForm(MedicamentType::class, $medicament); //Création du form

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $medicament->setDateAjout(new \DateTime());
            $manager->persist($medicament);
            $manager->flush();

           
            return $this->redirectToRoute('medicament');
        }

        return $this->render('medicament/formMedicament.html.twig', [
            'formMedicament' => $form->createView(),
            'ajout' => $ajout
        ]);
    }

    /**
     * Suppression medicament
     * 
     * @Route("/medicament/{id}/supprimer", name="supprimerMedicament")
     */
    public function remove(MedicamentRepository $repo, $id, ObjectManager $manager)
    {
        $medicament = $repo->find($id);
        $manager->remove($medicament);
        $manager->flush();

        return $this->redirectToRoute('medicament');
    }


}

gestionRapportVisites/templates/medicament/formMedicament.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste medicaments{% endblock %}

{% block body %}
<div class="fondgris">
    <div class="container corpformmed">

        <div class="columns">
            <div class="column is-2"></div>
            <div class="column">

                <div class="box">
                    <h1 class="title is-3 has-text-dark margform">
                        {% if ajout == true %}Ajouter{% else %}Modifier{% endif %}
                        un médicament</h1>
                    <h1 class="subtitle is-5 has-text-dark margform">----------------------------</h1>
                    <div class="margform">
                        {{ form_start(formMedicament) }}
                        {{ form_row(formMedicament.med_depot_legal) }}
                        {{ form_row(formMedicament.libelle) }}
                        {{ form_row(formMedicament.description) }}
                        <button type="submit" class="button is-primary" style="margin-top:6%;">
                            {% if ajout == true %}Ajouter{% else %}Modifier{% endif %}
                        </button>
                        {{ form_end(formMedicament) }}
                    </div>
                </div>
            </div>
            <div class="column is-2"></div>
        </div>

    </div>
</div>

{% endblock %}

gestionRapportVisites/templates/medicament/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
{% endblock %}
{% block title %}Liste medicaments{% endblock %}

{% block body %}
<div class="fondgris">
    <div class="container corp">
        <div class="columns">
            <div class="column is-offset-1">
                <a href="">
                    <h1 class="title is-3 has-text-white">Liste des médicaments</h1>
                </a>
                <h1 class="subtitle is-5 has-text-white">----------------------------</h1>
            </div>
            <div class="column is-1">
            </div>
        </div>

        <div class="columns">
            <div class="column is-3 is-offset-1">
                <a href="{{ path("ajouterMedicament") }}" class="button is-primary"><span class="icon"><i class="fas fa-plus"></i></span><span>Ajouter
                        un médicament</span></a>
            </div>
            <div class="column is-3 is-offset-3">
                {{ form_start(searchForm, {attr: {'id': 'idjava'}})}}
                {{ form_row(searchForm.search) }}
                <br>
                <div class="centerform">
                    {{ form_row(searchForm.dateSearch) }}
                    &nbsp;
                    <select id="locale">
                        <option value="ar">Arabic (&#8235;(&#1575;&#1604;&#1593;&#1585;&#1576;&#1610;&#1577;</option>
                        <option value="zh-TW">Chinese Traditional (&#32321;&#39636;&#20013;&#25991;)</option>
                        <option value="">English</option>
                        <option value="fr" selected="selected">French (Fran&ccedil;ais)</option>
                        <option value="he">Hebrew (&#8235;(&#1506;&#1489;&#1512;&#1497;&#1514;</option>
                    </select></p>
                </div>
            </div>
            <div class="column is-1">
                <button type="submit" class="button is-primary"><i class="fas fa-search"></i></button>
            </div>
            {{ form_end(searchForm) }}
        </div>

        <br><br>

        {% for medicament in medicaments %}
        <div class="columns">
            <div class="column is-offset-1">
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-64x64">
                                <img src="{{ medicament.image }}" alt="Image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <strong>N° {{ medicament.id }} : {{ medicament.libelle }}</strong>
                                    <br>
                                    Dépot légal : {{ medicament.medDepotLegal }}
                                    <br>
                                    Date d'ajout : {{ medicament.dateAjout | date("d/m/Y") }}
                                    <br>
                                    {{ medicament.description }}
                                </p>
                            </div>
                            <nav class="level is-mobile">
                                <div class="level-left">
                                    <a href="{{ path("modifierMedicament", {"id" : medicament.id }) }}" class="level-item"
                                        aria-label="modifier">
                                        <span class="icon is-small">
                                            <i class="fas fa-wrench"></i>
                                        </span>
                                    </a>
                                    <a href="{{ path("supprimerMedicament", {"id" : medicament.id }) }}" class="level-item"
                                        aria-label="suprimer" onclick="return confirm('Êtes-vous sûr ?')">
                                        <span class="icon is-small">
                                            <i class="fas fa-times"></i>
                                        </span>
                                    </a>
                                </div>
                            </nav>
                        </div>
                    </article>
                </div>
            </div>
            <div class="column is-1">
            </div>
        </div>
        <br><br>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block javascripts %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="i18n/datepicker-ar.js"></script>
<script src="i18n/datepicker-fr.js"></script>
<script src="i18n/datepicker-he.js"></script>
<script src="i18n/datepicker-zh-TW.js"></script>
<script>
    $(function () {
        $("#dateSearch").datepicker({


            dateFormat: 'dd/mm/yy',
            showAnim: 'blind'

        });
    });

    $("#locale").on("change", function () {
        $("#dateSearch").datepicker("option",
            $.datepicker.regional[$(this).val()]);
        console.log($(this).val());
    });

    $("#dateSearch").change(function () {
        $("#idjava").submit();
    });
</script>
{% endblock %}